package lk.vista.book.enums;

public enum BookCategory {
    CATEGORY_FICTION,
    CATEGORY_NONFICTION,
    CATEGORY_KIDS,
    CATEGORY_SCIENCE_TECHNOLOGY,
    CATEGORY_GRAPHIC_NOVELS_COMICS,
    CATEGORY_POETRY
}